CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    title VARCHAR(120) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    category_id BIGINT NOT NULL,
    initiator_id BIGINT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_on TIMESTAMP,

    CONSTRAINT fk_event_category
    FOREIGN KEY (category_id) REFERENCES categories(id),

    CONSTRAINT fk_event_initiator
    FOREIGN KEY (initiator_id) REFERENCES users(id),

    CONSTRAINT chk_event_state
    CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),

    CONSTRAINT chk_event_participant_limit
    CHECK (participant_limit >= 0)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    CONSTRAINT fk_request_event
    FOREIGN KEY (event_id) REFERENCES events(id),

    CONSTRAINT fk_request_requester
    FOREIGN KEY (requester_id) REFERENCES users(id),

    CONSTRAINT uq_request_event_requester
    UNIQUE (event_id, requester_id),

    CONSTRAINT chk_request_status
    CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_event_compilation
    FOREIGN KEY (compilation_id) REFERENCES compilations(id),
    CONSTRAINT fk_compilation_event_event
    FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    edited BOOLEAN NOT NULL DEFAULT FALSE,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,

    CONSTRAINT fk_comment_event
    FOREIGN KEY (event_id) REFERENCES events(id),

    CONSTRAINT fk_comment_author
    FOREIGN KEY (author_id) REFERENCES users(id),

    CONSTRAINT chk_comment_status
    CHECK (status IN ('PENDING', 'PUBLISHED', 'REJECTED'))
);